export default function AgbPage() {
      return (
          <main className="min-h-screen bg-black text-white px-6 py-16 max-w-2xl mx-auto">
                <h1 className="text-3xl font-bold tracking-tight mb-10">Allgemeine Geschäftsbedingungen</h1>

                      <section className="mb-8">
                              <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 1 Geltungsbereich</h2>
                                      <p className="text-zinc-400 leading-relaxed text-sm">
                                                Diese Allgemeinen Geschäftsbedingungen (AGB) gelten für alle Verträge zwischen der
                                                          KAYUYImedia UG (haftungsbeschränkt), Zum Vorberg 20, 27318 Hoyerhagen (nachfolgend
                                                                    „Anbieter") und den Nutzern der Plattform RELEVANT. (nachfolgend „Nutzer").
                                                                            </p>
                                                                                  </section>

                                                                                        <section className="mb-8">
                                                                                                <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 2 Leistungsbeschreibung</h2>
                                                                                                        <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                  RELEVANT. ist eine SaaS-Plattform zur Analyse und Messung der Social-Media-Relevanz
                                                                                                                            von Unternehmen und Marken. Der Anbieter stellt dem Nutzer Analysefunktionen,
                                                                                                                                      Dashboards und Berichte über eine webbasierte Oberfläche zur Verfügung.
                                                                                                                                              </p>
                                                                                                                                                    </section>

                                                                                                                                                          <section className="mb-8">
                                                                                                                                                                  <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 3 Vertragsschluss</h2>
                                                                                                                                                                          <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                    Der Vertrag kommt durch die Registrierung des Nutzers auf der Plattform und die
                                                                                                                                                                                              Bestätigung durch den Anbieter zustande. Mit der Registrierung akzeptiert der
                                                                                                                                                                                                        Nutzer diese AGB sowie die Datenschutzerklärung.
                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                            <section className="mb-8">
                                                                                                                                                                                                                                    <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 4 Nutzungsrechte</h2>
                                                                                                                                                                                                                                            <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                      Der Anbieter gewährt dem Nutzer ein nicht-exklusives, nicht-übertragbares Recht zur
                                                                                                                                                                                                                                                                Nutzung der Plattform im Rahmen des gebuchten Tarifs. Eine Weitergabe von
                                                                                                                                                                                                                                                                          Zugangsdaten an Dritte ist nicht gestattet.
                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                              <section className="mb-8">
                                                                                                                                                                                                                                                                                                      <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 5 Preise und Zahlung</h2>
                                                                                                                                                                                                                                                                                                              <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                        Die aktuellen Preise sind auf der Plattform einsehbar. Die Abrechnung erfolgt
                                                                                                                                                                                                                                                                                                                                  monatlich im Voraus. Zahlungen werden über den Zahlungsdienstleister Stripe
                                                                                                                                                                                                                                                                                                                                            abgewickelt. Alle Preise verstehen sich zzgl. der gesetzlichen Mehrwertsteuer.
                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 6 Laufzeit und Kündigung</h2>
                                                                                                                                                                                                                                                                                                                                                                                <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                          Das Abonnement läuft monatlich und kann jederzeit zum Ende des aktuellen
                                                                                                                                                                                                                                                                                                                                                                                                    Abrechnungszeitraums gekündigt werden. Die Kündigung erfolgt über die
                                                                                                                                                                                                                                                                                                                                                                                                              Kontoeinstellungen oder per E-Mail an{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="mailto:hello@getrelevant.app" className="text-yellow-400 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                    hello@getrelevant.app
                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>.
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 7 Haftungsbeschränkung</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Der Anbieter haftet nur für Schäden, die auf vorsätzlichem oder grob fahrlässigem
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Verhalten beruhen. Die Haftung für leichte Fahrlässigkeit ist ausgeschlossen, soweit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                keine wesentlichen Vertragspflichten verletzt werden. Die Haftung ist auf den
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          vertragstypisch vorhersehbaren Schaden begrenzt.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 8 Verfügbarkeit</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Der Anbieter strebt eine Verfügbarkeit der Plattform von 99 % pro Monat an.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Ausgenommen sind geplante Wartungsarbeiten sowie Ausfälle, die außerhalb des
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Einflussbereichs des Anbieters liegen.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 9 Änderungen der AGB</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Der Anbieter behält sich vor, diese AGB mit einer Frist von 30 Tagen zu ändern.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Nutzer werden per E-Mail über Änderungen informiert. Widerspricht der Nutzer nicht
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              innerhalb dieser Frist, gelten die neuen AGB als akzeptiert.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-lg font-semibold text-zinc-300 mb-2">§ 10 Anwendbares Recht</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Es gilt das Recht der Bundesrepublik Deutschland. Gerichtsstand ist, soweit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gesetzlich zulässig, der Sitz des Anbieters.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }