export default function ImpressumPage() {
      return (
          <main className="min-h-screen bg-black text-white px-6 py-16 max-w-2xl mx-auto">
                <h1 className="text-3xl font-bold tracking-tight mb-10">Impressum</h1>

                      <section className="mb-8">
                              <h2 className="text-lg font-semibold text-zinc-300 mb-2">Angaben gemäß § 5 TMG</h2>
                                      <p className="text-zinc-400 leading-relaxed">
                                                KAYUYImedia UG (haftungsbeschränkt)<br />
                                                          Zum Vorberg 20<br />
                                                                    27318 Hoyerhagen<br />
                                                                              Deutschland
                                                                                      </p>
                                                                                            </section>

                                                                                                  <section className="mb-8">
                                                                                                          <h2 className="text-lg font-semibold text-zinc-300 mb-2">Vertreten durch</h2>
                                                                                                                  <p className="text-zinc-400">Nikolai Sperling</p>
                                                                                                                        </section>

                                                                                                                              <section className="mb-8">
                                                                                                                                      <h2 className="text-lg font-semibold text-zinc-300 mb-2">Kontakt</h2>
                                                                                                                                              <p className="text-zinc-400 leading-relaxed">
                                                                                                                                                        Telefon: 04251 4429124<br />
                                                                                                                                                                  E-Mail:{' '}
                                                                                                                                                                            <a href="mailto:hello@getrelevant.app" className="text-yellow-400 hover:underline">
                                                                                                                                                                                        hello@getrelevant.app
                                                                                                                                                                                                  </a>
                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                      <section className="mb-8">
                                                                                                                                                                                                                              <h2 className="text-lg font-semibold text-zinc-300 mb-2">Registereintrag</h2>
                                                                                                                                                                                                                                      <p className="text-zinc-400 leading-relaxed">
                                                                                                                                                                                                                                                Eingetragen im Handelsregister.<br />
                                                                                                                                                                                                                                                          Registergericht: Amtsgericht Walsrode<br />
                                                                                                                                                                                                                                                                    Registernummer: HRB 207109
                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                        <section className="mb-8">
                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-semibold text-zinc-300 mb-2">Umsatzsteuer-ID</h2>
                                                                                                                                                                                                                                                                                                        <p className="text-zinc-400">
                                                                                                                                                                                                                                                                                                                  Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG: DE315917622
                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                      <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                              <h2 className="text-lg font-semibold text-zinc-300 mb-2">Haftung für Inhalte</h2>
                                                                                                                                                                                                                                                                                                                                                      <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                Als Diensteanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten
                                                                                                                                                                                                                                                                                                                                                                          nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als
                                                                                                                                                                                                                                                                                                                                                                                    Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde
                                                                                                                                                                                                                                                                                                                                                                                              Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige
                                                                                                                                                                                                                                                                                                                                                                                                        Tätigkeit hinweisen.
                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                            <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-lg font-semibold text-zinc-300 mb-2">Haftung für Links</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    der Seiten verantwortlich.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-semibold text-zinc-300 mb-2">Urheberrecht</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Zustimmung des jeweiligen Autors bzw. Erstellers.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
}