export default function DatenschutzPage() {
      return (
          <main className="min-h-screen bg-black text-white px-6 py-16 max-w-2xl mx-auto">
                <h1 className="text-3xl font-bold tracking-tight mb-10">Datenschutzerklärung</h1>

                      <section className="mb-8">
                              <h2 className="text-lg font-semibold text-zinc-300 mb-2">1. Verantwortlicher</h2>
                                      <p className="text-zinc-400 leading-relaxed text-sm">
                                                KAYUYImedia UG (haftungsbeschränkt)<br />
                                                          Zum Vorberg 20, 27318 Hoyerhagen<br />
                                                                    E-Mail:{' '}
                                                                              <a href="mailto:hello@getrelevant.app" className="text-yellow-400 hover:underline">
                                                                                          hello@getrelevant.app
                                                                                                    </a>
                                                                                                            </p>
                                                                                                                  </section>

                                                                                                                        <section className="mb-8">
                                                                                                                                <h2 className="text-lg font-semibold text-zinc-300 mb-2">2. Erhebung und Verarbeitung personenbezogener Daten</h2>
                                                                                                                                        <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                  Wir erheben und verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung
                                                                                                                                                            unserer Dienste erforderlich ist. Dazu gehören insbesondere:
                                                                                                                                                                    </p>
                                                                                                                                                                            <ul className="text-zinc-400 text-sm mt-2 ml-4 list-disc space-y-1">
                                                                                                                                                                                      <li>E-Mail-Adresse (für Authentifizierung und Kommunikation)</li>
                                                                                                                                                                                                <li>Nutzungsdaten (für die Bereitstellung der App-Funktionalität)</li>
                                                                                                                                                                                                          <li>Technische Daten (IP-Adresse, Browser-Informationen)</li>
                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                              <section className="mb-8">
                                                                                                                                                                                                                                      <h2 className="text-lg font-semibold text-zinc-300 mb-2">3. Rechtsgrundlage</h2>
                                                                                                                                                                                                                                              <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                        Die Verarbeitung Ihrer Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO
                                                                                                                                                                                                                                                                  (Vertragserfüllung) sowie Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse).
                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                      <section className="mb-8">
                                                                                                                                                                                                                                                                                              <h2 className="text-lg font-semibold text-zinc-300 mb-2">4. Weitergabe von Daten</h2>
                                                                                                                                                                                                                                                                                                      <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                Wir geben Ihre Daten nicht an Dritte weiter, es sei denn, dies ist zur Vertragserfüllung
                                                                                                                                                                                                                                                                                                                          notwendig oder gesetzlich vorgeschrieben. Wir nutzen folgende Dienstleister:
                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                          <ul className="text-zinc-400 text-sm mt-2 ml-4 list-disc space-y-1">
                                                                                                                                                                                                                                                                                                                                                    <li>Supabase (Authentifizierung und Datenbankhosting)</li>
                                                                                                                                                                                                                                                                                                                                                              <li>Vercel (Hosting)</li>
                                                                                                                                                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                  <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-lg font-semibold text-zinc-300 mb-2">5. Speicherdauer</h2>
                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                            Ihre Daten werden nur so lange gespeichert, wie es für die Erfüllung des jeweiligen
                                                                                                                                                                                                                                                                                                                                                                                                                      Zwecks erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen. Nach
                                                                                                                                                                                                                                                                                                                                                                                                                                Kündigung Ihres Kontos werden Ihre Daten innerhalb von 30 Tagen gelöscht.
                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                    <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-lg font-semibold text-zinc-300 mb-2">6. Ihre Rechte</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Sie haben das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Verarbeitung Ihrer personenbezogenen Daten. Außerdem haben Sie ein Widerspruchsrecht
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  sowie das Recht auf Datenübertragbarkeit. Wenden Sie sich dazu an:{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="mailto:hello@getrelevant.app" className="text-yellow-400 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hello@getrelevant.app
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-lg font-semibold text-zinc-300 mb-2">7. Cookies</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Wir verwenden technisch notwendige Cookies für die Authentifizierung und
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Sitzungsverwaltung. Diese Cookies sind für den Betrieb der App erforderlich und
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    können nicht deaktiviert werden.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-semibold text-zinc-300 mb-2">8. Beschwerderecht</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-zinc-400 leading-relaxed text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Sie haben das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Die zuständige Aufsichtsbehörde ist der Landesbeauftragte für den Datenschutz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Niedersachsen.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }